[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "demo"

[build.environment]
  NODE_VERSION = "18"

# Redirect all API calls to the main function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
